name: CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
    build:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-18.04, ubuntu-latest]
          python-version: ['3.6','3.7','3.8','3.9']
      steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge
      - run: conda --version
      - run: which python
      - name: "Run installation"
        run: |
         pip install -r requirements.txt
      - name: "Download data"
        run: |
         ./scripts/download_data.sh
      - name: "Run tests"
        run: |
         pytest --cov=./
      - name: "Upload coverage to Codecov"
        run:
         bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
      - name: "Node embedding"
        run: |
         python ./scripts/node_embedding.py preprocess ./data/tweet_ids/reply_network.txt --con 2 --rows 10000
         python ./scripts/node_embedding.py fit 2core_10000.csv --model NetMF
         wc -l NetMF*.csv
