name: Testing installation and codebase using Anaconda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: "Install dependencies"
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file env.yml --name base
    - name: "Test with pytest"
      run: |
        $CONDA/bin/pytest --cov --cov-report xml:coverage.xml --ignore install
    - name: "Upload code coverage"
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov 
        ./codecov -t "$CODECOV_TOKEN"
    - name: "Download data"
      run: |
        bash ./scripts/download_data.sh
        pushd data/public_data_2022-10-27
        head Pro-vaxxer_results/parameters.json
        popd
